### ISSUE TITLE
[US] 01-Créer un compte(parent)

### ISSUE THREAD

**Issue by Sabrrii** [Sabrrii/E-Music#2]
### Description

- En tant que Non Inscrit
  - je peux me créer un compte
  - afin d'être membre de l'école

### Critères d'acceptation

- [x] Mise en place de Spring security pour l'authentification
- [x] Création des classes Métier **Enfant** et **Parent**
- [x] Création du contrôleur et actions
- [x] Création des vues
- [x] Validation des données
- [x] Persistance
- [x] Envoi de mail
- [x] Vérification adresse mail
