### ISSUE TITLE
[US] 02-Ajouter son enfant

### ISSUE THREAD

**Issue by Sabrrii** [Sabrrii/E-Music#3]
### Description

- En tant que Parent
  - je peux ajouter mon enfant à mon compte
  - afin qu'il puisse accéder a ses cours

### Critères d'acceptation

- [x] L'enfant est visible sur le compte du parent
- [x] Création des vues
- [x] L'id du parent est visible dans la base de données de l'enfant
